sudo: required 
services: 
  - docker

before_install:
  - docker build -t dockberm/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true dockberm/docker-react npm run test -- --coverage